name: docker

on:
  push:
    branches:
      - main

env:
  GO_VERSION: "1.16"
  DOCKER_REGISTRY: "ghcr.io"

jobs:
  edge:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.DOCKER_REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push docker image
        run: |
          DOCKER_TAG=edge make docker
          docker push ${{ env.DOCKER_REGISTRY }}/goodwaygroup/gwvault:edge